# Generated by Django 5.1.3 on 2025-01-07 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RentedVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('contactno', models.CharField(blank=True, max_length=15, null=True)),
                ('vehicletype', models.CharField(blank=True, max_length=50, null=True)),
                ('rent', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RestaurantComplaintTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint', models.CharField(blank=True, max_length=20, null=True)),
                ('reply', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RoomTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomnumber', models.CharField(blank=True, max_length=20, null=True)),
                ('roomtype', models.CharField(blank=True, max_length=20, null=True)),
                ('bedtype', models.CharField(blank=True, max_length=20, null=True)),
                ('roomimage', models.FileField(blank=True, null=True, upload_to='roomimages/')),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('roomservice', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.CharField(blank=True, max_length=25, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Spot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placename', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('ticket', models.CharField(choices=[('free', 'Free'), ('paid', 'Paid')], max_length=10)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
